### ISSUE TITLE
#Precisão

### ISSUE THREAD

**Issue by nogueiralegacy** [soft-felipe/aed1-metodos-ordenacao#5]
Os valores de tempo são muito pequenos então é necessário se atentar se vai ser necessário realizar alguma atividade para aumentar a precisão

**Comment by soft-felipe** [comment]
Vou dar um push aqui na master e fazer uns testes, daí consigo checar se é uma boa aumentar as casas decimais

**Comment by nogueiralegacy** [comment]
Não há necessidade de realizar nenhuma atividade em relação a precisão
